/**
 * ApiEventos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BooleanRespuestaGeneral { 
    statusCode?: number;
    message?: string | null;
    data?: boolean;
}

