/**
 * ApiEventos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventoIsncritos } from './eventoIsncritos';


export interface EventoIsncritosListRespuestaGeneral { 
    statusCode?: number;
    message?: string | null;
    data?: Array<EventoIsncritos> | null;
}

