/**
 * ApiEventos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventoIsncritos { 
    idEvento?: number;
    nombre?: string | null;
    descripcion?: string | null;
    fechaHora?: string;
    ubicacion?: string | null;
    capacidad?: number | null;
    usuarios?: Array<number> | null;
}

