export * from './booleanRespuestaGeneral';
export * from './evento';
export * from './eventoIsncritos';
export * from './eventoIsncritosListRespuestaGeneral';
export * from './inscripcion';
export * from './int32RespuestaGeneral';
export * from './loginApp';
export * from './usuario';
export * from './usuarioRespuestaGeneral';
