/**
 * ApiEventos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Usuario { 
    idUsuario?: number;
    nombre?: string | null;
    email?: string | null;
    password?: string | null;
    fechaCreacion?: string | null;
}

